# Generated by Django 5.1 on 2024-11-01 03:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=64)),
                ('original_title', models.CharField(blank=True, max_length=64)),
                ('original_language', models.CharField(blank=True, max_length=4)),
                ('release_date', models.DateField(blank=True)),
                ('year', models.IntegerField()),
                ('director', models.CharField(blank=True, max_length=32)),
                ('starring', models.CharField(blank=True, max_length=128)),
                ('overview', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('upload', models.FileField(upload_to='user_imports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(blank=True, max_length=32)),
                ('cinema_or_tv', models.CharField(blank=True, max_length=7, null=True)),
                ('video_medium', models.CharField(blank=True, max_length=9, null=True)),
                ('tv_channel', models.CharField(blank=True, max_length=16)),
                ('streaming_platform', models.CharField(blank=True, max_length=16)),
                ('cinema', models.CharField(blank=True, max_length=32)),
                ('comments', models.TextField(blank=True, max_length=4096)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewings', to='journal.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
