# Generated by Django 5.1 on 2024-09-12 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='imdb',
            new_name='tmdb',
        ),
        migrations.AddField(
            model_name='film',
            name='original_title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewing',
            name='streaming_platform',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='film',
            name='starring',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
