# Generated by Django 5.1 on 2024-09-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_imdb_film_tmdb_film_original_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewing',
            old_name='city',
            new_name='location',
        ),
    ]
