# Generated by Django 5.1 on 2024-09-13 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_city_viewing_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewing',
            old_name='film_id',
            new_name='film',
        ),
    ]
