# Generated by Django 5.1 on 2024-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_film_tmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
