# Generated by Django 5.1 on 2024-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_viewing_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='cinema_or_tv',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='video_medium',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
