# Generated by Django 5.1 on 2024-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juser',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
